import { test, expect } from '@playwright/test';

test.use({
  serviceWorkers: 'block'
});

test('test', async ({ page }) => {
  await page.routeFromHAR('C:\\Users\\jianz\\OneDrive - 知微行易（上海）智能科技有限公司\\桌面\\CETATest\\ceta-skills-windows-amd64-2.0.27\\ceta-ai-skills-windows-amd64\\ceta-ai-skills\\ui-recorder-workspace\\network.har');
  await page.goto('https://bot.ceta.crm.duxing.cn/ui/login/basic?auth=basic');
  await page.getByRole('textbox', { name: '邮箱' }).click();
  await page.getByRole('textbox', { name: '邮箱' }).fill('jinjin.zhang@bizops.com.cn');
  await page.getByRole('textbox', { name: '密码' }).click();
  await page.getByRole('textbox', { name: '密码' }).fill('Test@123456');
  await page.getByRole('button', { name: '登 入' }).click();
  await page.getByRole('button', { name: '登 入' }).click();
  await page.locator('path').first().click();
  await page.getByRole('link', { name: '语音管理（组织树）' }).click();
  await page.getByRole('button', { name: '新增' }).click();
  await page.getByRole('link', { name: '历史录音' }).click();
  await page.getByRole('button', { name: '生成线索' }).click();
  await page.getByRole('link', { name: '线索管理' }).click();
  await page.getByRole('button', { name: '编 辑' }).click();
  await page.locator('#region').click();
  await page.locator('#region').fill('华南');
  await page.locator('.ant-select-selection-overflow').click();
  await page.locator('#rc_select_2').fill('客户');
  await page.getByText('客户介绍').click();
  await page.getByRole('button', { name: '新建客户' }).click();
  await page.locator('#customerNameSearch').click();
  await page.locator('#customerNameSearch').fill('自动化测试客户');
  await page.getByRole('dialog').getByRole('button', { name: '提 交' }).click();
  await page.getByRole('button', { name: '转化为商机' }).click();
  await page.locator('#opportunityName').click();
  await page.locator('#opportunityName').fill('自动化测试机会');
  await page.getByRole('textbox', { name: '请选择日期' }).click();
  await page.getByText('1', { exact: true }).first().click();
  await page.locator('#expectedAmount').click();
  await page.locator('#expectedAmount').fill('1200');
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('56');
  await page.getByLabel('线索管理').getByRole('button', { name: '提 交' }).click();
  await page.getByRole('button').nth(5).click();
  await page.locator('#cell-ACTION_COLUMN-686 > .table-action-cell > a > .ant-btn').first().click();
  await page.getByRole('menuitem', { name: 'ellipsis' }).click();
  await page.getByRole('link', { name: '报价管理' }).click();
  await page.getByRole('button', { name: '新增' }).click();
  await page.locator('input[name="quoteDate"]').click();
  await page.getByText('1', { exact: true }).nth(1).click();
  await page.locator('input[name="validUntil"]').click();
  await page.getByText('1', { exact: true }).nth(3).click();
  await page.locator('#rc_select_33').click();
  await page.locator('#rc_select_33_list_0').getByText('自动化测试机会').click();
  await page.locator('#rc_select_35').click();
  await page.locator('#rc_select_35').fill('sales');
  await page.locator('#rc_select_35_list_0').getByText('Sales Director').click();
  await page.getByRole('button', { name: '新增行' }).click();
  await page.locator('#productSubtable').getByRole('combobox').click();
  await page.locator('#rc_select_36').press('CapsLock');
  await page.locator('#rc_select_36').fill('CRM');
  await page.locator('#rc_select_36').press('CapsLock');
  await page.getByText('CetaCRM', { exact: true }).click();
  await page.locator('.ag-row-even.ag-row.ag-row-level-0.ag-row-position-absolute.ag-row-first.ag-row-last > div:nth-child(7)').click();
  await page.getByRole('row', { name: 'CetaCRM 1,788 人民币 按年 Increase' }).getByRole('spinbutton').fill('2');
  await page.locator('div').filter({ hasText: /^CetaCRM1,788人民币按年$/ }).nth(1).click();
  await page.getByRole('gridcell').filter({ hasText: /^$/ }).nth(5).dblclick();
  await page.getByRole('gridcell', { name: 'Increase Value Decrease Value' }).getByRole('spinbutton').fill('1');
  await page.locator('div').filter({ hasText: /^CetaCRM1,788%人民币按年20$/ }).nth(1).click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').click();
  await page.getByRole('spinbutton').fill('6');
  await page.getByRole('button', { name: '提交审批' }).click();
  await page.getByRole('button').filter({ hasText: /^$/ }).nth(2).click();
  await page.getByRole('link', { name: '商机管理' }).click();
  await page.locator('#cell-ACTION_COLUMN-783').getByRole('button', { name: '编辑' }).click();
  await page.getByRole('tab', { name: '相关' }).click();
  await page.getByRole('button', { name: '报价' }).click();
  await page.getByRole('tab', { name: '基本信息' }).click();
  await page.getByTitle('初步判断').click();
  await page.getByText('赢单', { exact: true }).click();
  await page.locator('#contractNumber').click();
  await page.locator('#contractNumber').fill('contract自动化测试编号');
  await page.getByRole('button', { name: '提交审批' }).click();
  await page.getByRole('button').nth(5).click();
  await page.getByRole('button').nth(5).click();
  await page.locator('#cell-ACTION_COLUMN-1056').getByRole('button', { name: '生成销售合同' }).click();
  await page.locator('.anticon > svg').click();
  await page.getByRole('link', { name: '合同管理' }).click();
  await page.locator('#cell-ACTION_COLUMN-1297').getByRole('button', { name: '查看' }).click();
  await page.getByRole('button', { name: '取 消' }).first().click();
  await page.locator('#cell-ACTION_COLUMN-1505').getByRole('button', { name: '编辑' }).click();
  await page.locator('#partyBName').click();
  await page.locator('#partyBName').fill('自动化测试乙方');
  await page.getByRole('button', { name: '生 效' }).click();
});